version: "3.9"

services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes: 
      - postgres:/var/lib/postgresql/data

  server:
    image: fastned-server:latest
    build:
        context: ./server
    depends_on:
        - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/prisma
    restart: "always"

  client:
    image: fastned-client:latest
    build:
        context: ./client
    restart: "always"

  gateway:
    image: fastned-gateway:latest
    build:
        context: ./gateway
    ports:
      - "3000:3000"
    restart: "always"

volumes:
    postgres: